# -*- coding: utf-8 -*-
"""
Created on Thu Feb 19 10:56:42 2026

@author: Kader SANOGO

cp_sat_solver_jsspt.py
----------------------

CP-SAT solver for JSSPT instances (without fatigue). This is a baseline.
Fatigue is expected to be added later on top of this structure.

- Loads one JSON instance created by the instance generators.
- Requires: pip install ortools


NOTE
----
This version ignores fatigue and delta, and uses the 'duration'
field from each operation as its processing time.

"""

from __future__ import annotations

import json
import math
import os
import time
from typing import Dict, List, Tuple, Optional

from ortools.sat.python import cp_model
import matplotlib.pyplot as plt


# ---------------------------------------------------------------------------
# Instance loading
# ---------------------------------------------------------------------------

def load_jsspt_instance(path: str) -> Dict:
    """
    Load a JSSPT JSON instance.

    Expected schema (as generated by convert_bu_to_jsspt_json.py):
    {
        "instance_id": "...",
        "scenario": "S1" or "S2",
        "layout_id": int,
        "layout_name": str,
        "robots_nb": int,
        "machines_nb": int,
        "locations": [...],
        "sigma": [[...]],
        "jobs": [
            {
                "job_id": "J1",
                "job_index": 1,
                "n_ops": 3,
                "ops": [
                    {"op_id": "O1_1", "op_index": 1,
                     "machine_id": "M1", "machine_index": 1,
                     "duration": 8, ...},
                    ...
                ]
            },
            ...
        ],
        "meta": {...}
    }
    """
    with open(path, "r") as f:
        data = json.load(f)

    return data


# ---------------------------------------------------------------------------
# CP-SAT solver
# ---------------------------------------------------------------------------

def solve_jsspt_cp(
    instance: Dict,
    last_ttask: int = 1,
    num_robots: Optional[int] = None,
    time_limit: float = 600.0,
    num_workers: int = 8,
    make_gantt: bool = True,
    gantt_path: Optional[str] = None,
) -> Tuple[str, Optional[int], float]:
    """
    Solve the JSSPT instance with CP-SAT.

    Parameters
    ----------
    instance : dict
        Parsed JSON instance.
    last_ttask : int
        1  -> include final return-to-Z transport per job
        0  -> ignore final return-to-Z.
    num_robots : int or None
        If None, use instance["robots_nb"]. Otherwise override.
    time_limit : float
        Solver time limit in seconds.
    num_workers : int
        Number of search workers for CP-SAT (parallelism).
    make_gantt : bool
        Whether to generate a Gantt chart.
    gantt_path : Optional[str]
        File path to save the Gantt figure (PNG). If None, use a default
        name derived from the instance id.

    Returns
    -------
    (status_str, C_max, cpu_time)
    """
    # -------------------------
    # Basic instance data
    # -------------------------
    inst_id = instance.get("instance_id", "unknown_instance")
    layout_id = instance.get("layout_id", -1)
    layout_name = instance.get("layout_name", "")
    M = instance["machines_nb"]
    sigma = instance["sigma"]  # (M+1)x(M+1), index 0=Z, 1..M=machines
    jobs_data = instance["jobs"]

    if num_robots is None:
        R = instance.get("robots_nb", 1)
    else:
        R = num_robots

    # -------------------------
    # Build operation data
    # -------------------------
    # We work with 0-based indexes internally:
    # job i in 0..J-1, op j in 0..(n_ops_i-1)
    J = len(jobs_data)

    op_duration: Dict[Tuple[int, int], int] = {}
    op_machine: Dict[Tuple[int, int], int] = {}
    job_n_ops: List[int] = []

    total_proc_time = 0
    for i, job in enumerate(jobs_data):
        n_ops = job["n_ops"]
        job_n_ops.append(n_ops)
        for j, op in enumerate(job["ops"]):
            m_idx = op["machine_index"]  # 1..M
            dur = int(op["duration"])
            op_machine[(i, j)] = m_idx
            op_duration[(i, j)] = dur
            total_proc_time += dur

    # -------------------------
    # Build transport tasks
    # -------------------------
    # Each op (i,j) has a preceding transport T(i,j).
    # We also optionally add T_fp(i) : last job transport back to Z.
    #
    # We'll index all transports by t in 0..T-1 and record:
    #   t_job[t], t_op[t]   (op index or -1 for final return)
    #   t_pickup[t], t_drop[t]  (location indexes 0..M)
    #   t_duration[t]
    # plus maps (i,j)->t_index and (i,'ret')->t_index
    t_job: List[int] = []
    t_op: List[int] = []
    t_pickup: List[int] = []
    t_drop: List[int] = []
    t_duration: List[int] = []

    trans_of_op: Dict[Tuple[int, int], int] = {}
    trans_of_ret: Dict[int, int] = {}

    for i in range(J):
        n_ops = job_n_ops[i]
        for j in range(n_ops):
            if j == 0:
                pickup = 0  # Z
            else:
                pickup = op_machine[(i, j - 1)]
            drop = op_machine[(i, j)]
            dur = int(sigma[pickup][drop])
            idx = len(t_job)
            t_job.append(i)
            t_op.append(j)
            t_pickup.append(pickup)
            t_drop.append(drop)
            t_duration.append(dur)
            trans_of_op[(i, j)] = idx

        if last_ttask == 1:
            # Final return to Z from last machine
            pickup = op_machine[(i, n_ops - 1)]
            drop = 0
            dur = int(sigma[pickup][drop])
            idx = len(t_job)
            t_job.append(i)
            t_op.append(-1)  # final return
            t_pickup.append(pickup)
            t_drop.append(drop)
            t_duration.append(dur)
            trans_of_ret[i] = idx

    T = len(t_job)
    max_sigma = max(max(row) for row in sigma)
    horizon = total_proc_time + T * max_sigma + 10

    # -------------------------
    # CP-SAT model
    # -------------------------
    model = cp_model.CpModel()

    # ----- operation variables -----
    op_start: Dict[Tuple[int, int], cp_model.IntVar] = {}
    op_end: Dict[Tuple[int, int], cp_model.IntVar] = {}
    op_interval: Dict[Tuple[int, int], cp_model.IntervalVar] = {}
    machine_intervals: Dict[int, List[cp_model.IntervalVar]] = {
        m: [] for m in range(1, M + 1)
    }

    for i in range(J):
        for j in range(job_n_ops[i]):
            dur = op_duration[(i, j)]
            start = model.NewIntVar(0, horizon, f"S_{i}_{j}")
            end = model.NewIntVar(0, horizon, f"C_{i}_{j}")
            model.Add(end == start + dur)
            interval = model.NewIntervalVar(start, dur, end, f"I_{i}_{j}")
            op_start[(i, j)] = start
            op_end[(i, j)] = end
            op_interval[(i, j)] = interval
            m_idx = op_machine[(i, j)]
            machine_intervals[m_idx].append(interval)

    # Machines: no overlap
    for m in range(1, M + 1):
        model.AddNoOverlap(machine_intervals[m])

    # ----- transport variables -----
    t_start: List[cp_model.IntVar] = []
    t_end: List[cp_model.IntVar] = []
    t_interval: List[cp_model.IntervalVar] = []
    for t in range(T):
        dur = t_duration[t]
        s = model.NewIntVar(0, horizon, f"TS_{t}")
        e = model.NewIntVar(0, horizon, f"TC_{t}")
        model.Add(e == s + dur)
        iv = model.NewIntervalVar(s, dur, e, f"TI_{t}")
        t_start.append(s)
        t_end.append(e)
        t_interval.append(iv)

    # robot assignment: robot_assign[r][t] in {0,1}
    robot_assign: List[List[cp_model.BoolVar]] = []
    for r in range(R):
        row = []
        for t in range(T):
            var = model.NewBoolVar(f"r{r}_t{t}")
            row.append(var)
        robot_assign.append(row)

    # Each transport assigned to exactly one robot
    for t in range(T):
        model.Add(sum(robot_assign[r][t] for r in range(R)) == 1)

    # ----- precedence: transport vs processing -----
    for i in range(J):
        n_ops = job_n_ops[i]
        for j in range(n_ops):
            t_idx = trans_of_op[(i, j)]
            # processing cannot start before transport is done
            model.Add(op_start[(i, j)] >= t_end[t_idx])
            # next transport cannot start before this processing ends
            if j > 0:
                model.Add(t_start[t_idx] >= op_end[(i, j - 1)])
            else:
                # first transport has only the initial-position constraint (below)
                pass

        if last_ttask == 1:
            # final return starts after last operation
            t_ret = trans_of_ret[i]
            model.Add(t_start[t_ret] >= op_end[(i, n_ops - 1)])

    # ----- robots: sequence-dependent empty travel -----
    bigM = horizon

    for r in range(R):
        for t in range(T):
            # Initial positioning from Z to the pickup of task t.
            pickup = t_pickup[t]
            travel0 = int(sigma[0][pickup])
            # If transport t is assigned to robot r, it cannot start before
            # the empty travel from Z to its pickup.
            model.Add(t_start[t] >= travel0 * robot_assign[r][t])

        # Sequence-dependent empty travel between any two transports on robot r
        for t1 in range(T):
            for t2 in range(t1 + 1, T):
                # Boolean z_r_t1_t2 = 1 if BOTH t1 and t2 are assigned to r
                z = model.NewBoolVar(f"both_r{r}_t{t1}_t{t2}")
                model.Add(z <= robot_assign[r][t1])
                model.Add(z <= robot_assign[r][t2])
                model.Add(z >= robot_assign[r][t1] + robot_assign[r][t2] - 1)

                # y12 = 1 if on robot r, t1 is executed before t2
                # y21 = 1 if on robot r, t2 is executed before t1
                y12 = model.NewBoolVar(f"y_r{r}_t{t1}_t{t2}")
                y21 = model.NewBoolVar(f"y_r{r}_t{t2}_t{t1}")

                # They can only be 1 when both tasks are on r
                model.Add(y12 <= z)
                model.Add(y21 <= z)

                # If both are on r, exactly one orientation is chosen
                model.Add(y12 + y21 == z)

                # Sequence-dependent empty travel times
                drop1 = t_drop[t1]
                pick2 = t_pickup[t2]
                drop2 = t_drop[t2]
                pick1 = t_pickup[t1]
                empty_12 = int(sigma[drop1][pick2])
                empty_21 = int(sigma[drop2][pick1])

                # If y12 = 1: t2 starts after t1 end + empty_12
                model.Add(
                    t_start[t2] >= t_end[t1] + empty_12 - bigM * (1 - y12)
                )
                # If y21 = 1: t1 starts after t2 end + empty_21
                model.Add(
                    t_start[t1] >= t_end[t2] + empty_21 - bigM * (1 - y21)
                )

    # ----- makespan -----
    job_completion = []
    for i in range(J):
        if last_ttask == 1:
            job_completion.append(t_end[trans_of_ret[i]])
        else:
            job_completion.append(op_end[(i, job_n_ops[i] - 1)])

    C_max = model.NewIntVar(0, horizon, "Cmax")
    model.AddMaxEquality(C_max, job_completion)
    model.Minimize(C_max)

    # -------------------------
    # Solve
    # -------------------------
    solver = cp_model.CpSolver()
    solver.parameters.max_time_in_seconds = float(time_limit)
    solver.parameters.num_search_workers = num_workers

    print(f"Solving instance {inst_id} with {R} robots, last_ttask={last_ttask}...")
    start_time = time.time()
    status = solver.Solve(model)
    cpu_time = time.time() - start_time

    status_map = {
        cp_model.OPTIMAL: "OPTIMAL",
        cp_model.FEASIBLE: "FEASIBLE",
        cp_model.INFEASIBLE: "INFEASIBLE",
        cp_model.MODEL_INVALID: "MODEL_INVALID",
        cp_model.UNKNOWN: "UNKNOWN",
    }
    status_str = status_map.get(status, "UNKNOWN")

    if status in (cp_model.OPTIMAL, cp_model.FEASIBLE):
        cmax_val = int(solver.Value(C_max))
        print(f"  Status={status_str}, Cmax={cmax_val}, CPU={cpu_time:.2f}s")
    else:
        print(f"  Status={status_str}, CPU={cpu_time:.2f}s")
        return status_str, None, cpu_time

    # -------------------------
    # Extract schedule for Gantt
    # -------------------------
    # machine schedule: list of [machine, job, start, end, op_index]
    machine_sched: List[List[int]] = []
    for i in range(J):
        for j in range(job_n_ops[i]):
            m_idx = op_machine[(i, j)]
            s = solver.Value(op_start[(i, j)])
            e = solver.Value(op_end[(i, j)])
            machine_sched.append([m_idx, i + 1, s, e, j + 1])  # 1-based for plotting

    # robot schedule: [robot_id(1..R), job_id(1..J), start, end, op_index or 99 for final]
    robot_sched: List[List[int]] = []
    for t in range(T):
        # find robot that executes t
        assigned_robot = None
        for r in range(R):
            if solver.Value(robot_assign[r][t]) == 1:
                assigned_robot = r
                break
        if assigned_robot is None:
            continue  # should not happen

        i = t_job[t]
        op_index = t_op[t]
        if op_index == -1:
            op_label = 99  # final return
        else:
            op_label = op_index + 1  # 1-based

        s = solver.Value(t_start[t])
        e = solver.Value(t_end[t])
        robot_sched.append([assigned_robot + 1, i + 1, s, e, op_label])

    # -------------------------
    # Gantt chart
    # -------------------------
    if make_gantt:
        _plot_gantt(
            inst_id=inst_id,
            layout_id=layout_id,
            cmax_value=cmax_val,
            machine_sched=machine_sched,
            robot_sched=robot_sched,
            num_machines=M,
            num_robots=R,
            last_ttask=last_ttask,
            gantt_path=gantt_path,
        )

    return status_str, cmax_val, cpu_time


# ---------------------------------------------------------------------------
# Gantt plotting
# ---------------------------------------------------------------------------

def _plot_gantt(
    inst_id: str,
    layout_id: int,
    cmax_value: int,
    machine_sched: List[List[int]],
    robot_sched: List[List[int]],
    num_machines: int,
    num_robots: int,
    last_ttask: int,
    gantt_path: Optional[str],
):
    """
    Plot a Gantt chart.

    machine_sched: [M_id, Job_id, start, end, op_idx]
    robot_sched  : [R_id, Job_id, start, end, op_idx (99 for final)]
    """
    fig, ax = plt.subplots(figsize=(20, 8))

    mcolors = [
        "tab:red",
        "tab:cyan",
        "tab:green",
        "tab:orange",
        "tab:grey",
        "yellow",
        "tab:brown",
        "magenta",
        "lime",
        "tomato",
        "tab:blue",
        "red",
        "cyan",
        "green",
        "blue",
    ]

    # Y-axis ticks: machines first, then robots
    total_lines = num_machines + num_robots
    yticks = []
    setticks = []
    for k in range(total_lines):
        yticks.append(10 * (k + 1))
        setticks.append(10 * (k + 1) + 5)
    ax.set_yticks(setticks)

    ylabels = []
    for m in range(num_machines):
        ylabels.append(f"M{m+1}")
    for r in range(num_robots):
        ylabels.append(f"R{r+1}")
    ax.set_yticklabels(ylabels, fontsize=16)

    ax.set_xlabel("Time", fontsize=18, weight="bold")
    ax.tick_params(labelsize=14)

    ax.minorticks_on()
    ax.grid(which="major", linestyle="-", linewidth=0.5, color="red")
    ax.grid(which="minor", linestyle=":", linewidth=0.5, color="black")
    ax.set_xlim(0, int(cmax_value) + 10)

    # Machines
    for m in machine_sched:
        machine_id, job_id, start, end, op_idx = m
        a = [(start, end - start)]
        color = mcolors[(job_id - 1) % len(mcolors)]
        text = r"$O_{%d,%d}$" % (job_id, op_idx)
        x = start + (end - start) / 2 - 2
        y = 4 + yticks[machine_id - 1]
        ax.text(x, y, text, fontsize=14, weight="bold")
        ax.broken_barh(a, (yticks[machine_id - 1], 9), facecolors=color)

    # Robots
    for r in robot_sched:
        robot_id, job_id, start, end, op_idx = r
        a = [(start, end - start)]
        color = mcolors[(job_id - 1) % len(mcolors)]
        if op_idx == 99:
            text = r"$T^R_{J%d}$" % job_id
        else:
            text = r"$T_{%d,%d}$" % (job_id, op_idx)
        x = start + (end - start) / 2 - 2
        y = 4 + yticks[num_machines + robot_id - 1]
        ax.text(x, y, text, fontsize=14, weight="bold")
        ax.broken_barh(a, (yticks[num_machines + robot_id - 1], 9), facecolors=color)

    title = f"{inst_id}\nCmax={cmax_value}, last_ttask={last_ttask}"
    ax.set_title(title, fontsize=20, weight="bold")
    plt.tight_layout()

    if gantt_path is None:
        fname = f"{inst_id}_gantt.png"
    else:
        fname = gantt_path
    plt.savefig(fname, dpi=300)
    #plt.show()
    plt.close(fig)
    print(f"Gantt chart saved to: {fname}")


# ---------------------------------------------------------------------------
# Usage
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    # Example: solve one S1 instance
    # Adjust these paths to your environment
    root = "bu_instances_eval/scenario_1"
    inst_name = "EX5_2_S1.json"  # e.g. jobset 8, layout 2, scenario 1
    inst_path = os.path.join(root, inst_name)

    instance = load_jsspt_instance(inst_path)

    status, cmax, cpu = solve_jsspt_cp(
        instance,
        last_ttask=1,
        num_robots=2,          # override if you want
        time_limit=600.0,
        num_workers=8,
        make_gantt=True,
        gantt_path=None,
    )
    print("Done:", status, cmax, f"{cpu:.2f}s")

